spring:
  application:
    name: FlashcardsApp
  profiles:
    active: default
  banner:
    location: classpath:logo-app

pl:
  edu:
    pja:
      tpo02:
        filename: src/main/resources/dictionary.csv